In [50]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import random as rd

In [51]:
df=pd.read_csv(path)

In [52]:
df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [53]:
path = r"C:\Users\HP\Desktop\AI_project\kc_house_data.csv"

# df= pd.read_csv(path,usecols=['sqft_living','price'])

In [54]:
df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [56]:
df.iloc[:, 1:].corr()

ValueError: could not convert string to float: '20141013T000000'

In [57]:
df.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='str')

In [64]:
y = df['price']
x = df[['sqft_living' ,  'floors' , 'waterfront' , 'view' , 'condition' , 'grade' , 'sqft_above' , 'sqft_basement' , 'yr_built' , 'yr_renovated' , 'zipcode' , 'lat' , 'long' , 'sqft_living15' , 'sqft_lot15']]

In [65]:
x.info()

<class 'pandas.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   sqft_living    21613 non-null  int64
 1   floors         21613 non-null  float64
 2   waterfront     21613 non-null  int64
 3   view           21613 non-null  int64
 4   condition      21613 non-null  int64
 5   grade          21613 non-null  int64
 6   sqft_above     21613 non-null  int64
 7   sqft_basement  21613 non-null  int64
 8   yr_built       21613 non-null  int64
 9   yr_renovated   21613 non-null  int64
 10  zipcode        21613 non-null  int64
 11  lat            21613 non-null  float64
 12  long           21613 non-null  float64
 13  sqft_living15  21613 non-null  int64
 14  sqft_lot15     21613 non-null  int64
dtypes: float64(3), int64(12)
memory usage: 2.5 MB

In [66]:
x.shape

(21613, 15)

In [67]:
y.shape

(21613,)

In [ ]:
x.loc[:, 'sqft_living'])

In [76]:
for col in  x.columns:
    x[col] = x.[col].astype(float)
    x[col] = x[col]/x[col].max()

SyntaxError: invalid syntax (3046507398.py, line 2)

In [77]:
x

,sqft_living,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,0.087149,0.285714,0.0,0.0,0.6,0.538462,0.125399,0.000000,0.970223,0.000000,0.999786,0.994424,0.997862,0.215781,0.006485
1,0.189808,0.571429,0.0,0.0,0.6,0.538462,0.230606,0.082988,0.968238,0.988089,0.999246,0.998815,0.998368,0.272142,0.008768
2,0.056869,0.285714,0.0,0.0,0.6,0.461538,0.081828,0.000000,0.959305,0.000000,0.998259,0.999169,0.997666,0.438003,0.009254
3,0.144756,0.285714,0.0,0.0,1.0,0.538462,0.111583,0.188797,0.975186,0.000000,0.999358,0.994625,0.998972,0.219002,0.005739
4,0.124077,0.285714,0.0,0.0,0.6,0.615385,0.178533,0.000000,0.986104,0.000000,0.998727,0.996634,0.996131,0.289855,0.008612
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,0.112999,0.857143,0.0,0.0,0.6,0.615385,0.162593,0.000000,0.997022,0.000000,0.999022,0.998361,0.998588,0.246377,0.001732
21609,0.170606,0.571429,0.0,0.0,0.6,0.615385,0.245484,0.000000,0.999504,0.000000,0.999460,0.994414,0.998719,0.294686,0.008264
21610,0.075332,0.571429,0.0,0.0,0.6,0.538462,0.108395,0.000000,0.997022,0.000000,0.999440,0.996166,0.998204,0.164251,0.002304
21611,0.118168,0.571429,0.0,0.0,0.6,0.615385,0.170032,0.000000,0.994541,0.000000,0.998248,0.994912,0.996327,0.227053,0.001477
21612,0.075332,0.571429,0.0,0.0,0.6,0.538462,0.108395,0.000000,0.996526,0.000000,0.999440,0.996159,0.998204,0.164251,0.001558